services:
  - type: web
    name: mautic
    env: docker
    plan: free
    branch: main
    repo: Mamadou13S/mautic/
    dockerfilePath: Dockerfile
    envVars:
      - key: MAUTIC_DB_HOST
        value: db.meonqtadjeyunghqoegy.supabase.co
      - key: MAUTIC_DB_NAME
        value: postgres
      - key: MAUTIC_DB_USER
        value: postgres
      - key: MAUTIC_DB_PASSWORD
        value: V&Q4rjh.fDmVDa)
      - key: MAUTIC_ENV
        value: dev
